Project 6
========================================================
Helmich        Sam shelmich,  Zhou        Sen  senzhou, Chang   Jennifer jenchang

Summary of Project

Code for Sam Helmich
```{r}
library(RSQLite)
library(dplyr)

# This part runs
my_db <- src_sqlite("my_db.sqlite3", create = T)
nov <- read.csv("november.csv")
dec <- read.csv("december.csv")
data <- rbind(nov, dec)
hflights_sqlite <- copy_to(my_db, data, temporary = FALSE)
rm(nov, dec, data)

tbl_vars(hflights_sqlite)

# We'll go with LAX
# LAX ID = 12892
lax <- as.data.frame(hflights_sqlite %.%
          filter(ORIGIN_AIRPORT_ID == 12892 | DEST_AIRPORT_ID == 12892) %.%
          group_by(DAY_OF_WEEK) %.%
          select(DAY_OF_WEEK, DEP_DELAY, DEP_TIME, ARR_DELAY, ARR_TIME))
          
lax$sch.depart <- with(lax, DEP_TIME - DEP_DELAY)
lax$sch.arr <- with(lax, ARR_TIME - ARR_DELAY)
library(ggplot2)

qplot(DEP_TIME,DEP_DELAY, data = lax, facets = .~DAY_OF_WEEK, main = "Departures")
qplot(ARR_TIME, ARR_DELAY, data = lax, facets = .~DAY_OF_WEEK, main = "Arrivals")

```

Code for Jennifer Chang
```{r fig.width=7, fig.height=6}
data_loc<-"/Users/jenchang/Desktop/STAT585/Projects/Proj6/"

# install & load required packages
install.packages('dplyr')
install.packages('RSQLite')
install.packages("RSQLite.extfuns")
library(dplyr)
library(RSQLite)
library(RSQLite.extfuns)


# Load Data
nov <- read.csv("/Users/jenchang/Desktop/STAT585/Projects/Proj6/data/november2013.csv")
dec <- read.csv("/Users/jenchang/Desktop/STAT585/Projects/Proj6/dec2013.csv")

# connect to database and move data over
my_db <- src_sqlite("my_db.sqlite3", create = T)
hflights_sqlite <- copy_to(my_db, nov, temporary = FALSE)

# focus on LAX 12892
LAX_flights<-filter(hflights_sqlite,ORIGIN_AIRPORT_ID == 12892 | DEST_AIRPORT_ID == 12892)
out_df <-collect(LAX_flights)
dep<-filter(hflights_sqlite,ORIGIN_AIRPORT_ID==12892)
dep_df<-collect(dep)
arr<-filter(hflights_sqlite,DEST_AIRPORT_ID==12892)
arr_df<-collect(arr)

# Plot
library(ggplot2)
qplot(DAY_OF_WEEK, DEP_DELAY, data=dep_df)

# create table
dbGetQuery(co, "CREATE TABLE IF NOT EXISTS nd_flights (
  obs INT PRIMARY KEY NOT NULL,
  totbill DOUBLE,
  tip DOUBLE,
  sex CHAR(1),
  smoker CHAR(3),
  day CHAR(3),
  time CHAR(5),
  size INT
  )")

# open sqlite connection
my_db <- src_sqlite(“mydb.sqlite3”, create=T)

# load your data into database & setting indexes
yourdata_sqlite <- copy_to(my_db, yourdata, temporary=FALSE, indexes = list( c(“col1”, “col2”), col3))
yourdata_sqlite_df <- tbl(my_db, sql(“SELECT * from yourdata”))  # do we need this?

# ===  Basic Actions (VERBS) === looks the same as above!!!! <3
filter( yourdata_sqlite_df, col1==”value1”, col2==”value2”)  # filter data by column values
arrange( yourdata_sqlite_df, col2, col4)                                   # arrange data rows by column values
select( yourdata_sqlite_df, col2,col4)                                       # select certain columns of data 
mutate( yourdata_sqlite_df, diff = col2 - col4, percentage = col2 / col4)  # mutate, adding columns
summarize( yourdata_sqlite_df, avg = mean(col2, na.rm=TRUE)   # summarize a column of values

# get tbl_df of results using collect (sql statements not executed on database until R needs to print it out)
out <- select( yourdata_sqlite_df, col2,col4)
your_final_data_df <-collect(out)

# close sqlite connection
dbDisconnect(my_db)

```

